//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netnr.UAParser.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Netnr.UAParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;Entities xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;&lt;ListClient&gt;&lt;CE&gt;&lt;T&gt;browsers&lt;/T&gt;&lt;R&gt;InspectBrowser&lt;/R&gt;&lt;N&gt;Inspect Browser&lt;/N&gt;&lt;V /&gt;&lt;/CE&gt;&lt;CE&gt;&lt;T&gt;browsers&lt;/T&gt;&lt;R&gt;Keepsafe Browser&lt;/R&gt;&lt;N&gt;Keepsafe Browser&lt;/N&gt;&lt;V /&gt;&lt;/CE&gt;&lt;CE&gt;&lt;T&gt;browsers&lt;/T&gt;&lt;R&gt;(.*)Vast Browser/(\d+\.[\.\d]+)&lt;/R&gt;&lt;N&gt;Vast Browser&lt;/N&gt;&lt;V&gt;$2&lt;/V&gt;&lt;E&gt;Blink&lt;/E&gt;&lt;/CE&gt;&lt;CE&gt;&lt;T&gt;browsers&lt;/T&gt;&lt;R&gt;bloket&lt;/R&gt;&lt;N&gt;Bloket&lt;/N&gt;&lt;V /&gt;&lt;E&gt;Blink&lt;/E&gt;&lt;/CE&gt;&lt;CE&gt;&lt;T&gt;browsers&lt;/T&gt;&lt;R&gt;(.*)U Browser( [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string regexes {
            get {
                return ResourceManager.GetString("regexes", resourceCulture);
            }
        }
    }
}
