import * as monaco from 'monaco-old';

// import 'monaco-old/esm/vs/basic-languages/abap/abap'
// import 'monaco-old/esm/vs/basic-languages/apex/apex'
// import 'monaco-old/esm/vs/basic-languages/azcli/azcli'
import 'monaco-old/esm/vs/basic-languages/bat/bat'
// import 'monaco-old/esm/vs/basic-languages/bicep/bicep'
// import 'monaco-old/esm/vs/basic-languages/cameligo/cameligo'
// import 'monaco-old/esm/vs/basic-languages/clojure/clojure'
import 'monaco-old/esm/vs/basic-languages/coffee/coffee'
import 'monaco-old/esm/vs/basic-languages/cpp/cpp'
import 'monaco-old/esm/vs/basic-languages/csharp/csharp'
// import 'monaco-old/esm/vs/basic-languages/csp/csp'
import 'monaco-old/esm/vs/basic-languages/css/css'
// import 'monaco-old/esm/vs/basic-languages/cypher/cypher'
import 'monaco-old/esm/vs/basic-languages/dart/dart'
import 'monaco-old/esm/vs/basic-languages/dockerfile/dockerfile'
// import 'monaco-old/esm/vs/basic-languages/ecl/ecl'
// import 'monaco-old/esm/vs/basic-languages/elixir/elixir'
// import 'monaco-old/esm/vs/basic-languages/flow9/flow9'
// import 'monaco-old/esm/vs/basic-languages/freemarker2/freemarker2'
import 'monaco-old/esm/vs/basic-languages/fsharp/fsharp'
import 'monaco-old/esm/vs/basic-languages/go/go'
import 'monaco-old/esm/vs/basic-languages/graphql/graphql'
import 'monaco-old/esm/vs/basic-languages/handlebars/handlebars'
// import 'monaco-old/esm/vs/basic-languages/hcl/hcl'
import 'monaco-old/esm/vs/basic-languages/html/html'
import 'monaco-old/esm/vs/basic-languages/ini/ini'
import 'monaco-old/esm/vs/basic-languages/java/java'
import 'monaco-old/esm/vs/basic-languages/javascript/javascript'
// import 'monaco-old/esm/vs/basic-languages/julia/julia'
import 'monaco-old/esm/vs/basic-languages/kotlin/kotlin'
import 'monaco-old/esm/vs/basic-languages/less/less'
// import 'monaco-old/esm/vs/basic-languages/lexon/lexon'
// import 'monaco-old/esm/vs/basic-languages/liquid/liquid'
import 'monaco-old/esm/vs/basic-languages/lua/lua'
// import 'monaco-old/esm/vs/basic-languages/m3/m3'
import 'monaco-old/esm/vs/basic-languages/markdown/markdown'
// import 'monaco-old/esm/vs/basic-languages/mdx/mdx'
// import 'monaco-old/esm/vs/basic-languages/mips/mips'
// import 'monaco-old/esm/vs/basic-languages/msdax/msdax'
import 'monaco-old/esm/vs/basic-languages/mysql/mysql'
import 'monaco-old/esm/vs/basic-languages/objective-c/objective-c'
import 'monaco-old/esm/vs/basic-languages/pascal/pascal'
// import 'monaco-old/esm/vs/basic-languages/pascaligo/pascaligo'
import 'monaco-old/esm/vs/basic-languages/perl/perl'
import 'monaco-old/esm/vs/basic-languages/pgsql/pgsql'
import 'monaco-old/esm/vs/basic-languages/php/php'
// import 'monaco-old/esm/vs/basic-languages/pla/pla'
// import 'monaco-old/esm/vs/basic-languages/postiats/postiats'
// import 'monaco-old/esm/vs/basic-languages/powerquery/powerquery'
import 'monaco-old/esm/vs/basic-languages/powershell/powershell'
import 'monaco-old/esm/vs/basic-languages/protobuf/protobuf'
// import 'monaco-old/esm/vs/basic-languages/pug/pug'
import 'monaco-old/esm/vs/basic-languages/python/python'
import 'monaco-old/esm/vs/basic-languages/qsharp/qsharp'
import 'monaco-old/esm/vs/basic-languages/r/r'
import 'monaco-old/esm/vs/basic-languages/razor/razor'
import 'monaco-old/esm/vs/basic-languages/redis/redis'
import 'monaco-old/esm/vs/basic-languages/redshift/redshift'
// import 'monaco-old/esm/vs/basic-languages/restructuredtext/restructuredtext'
import 'monaco-old/esm/vs/basic-languages/ruby/ruby'
import 'monaco-old/esm/vs/basic-languages/rust/rust'
// import 'monaco-old/esm/vs/basic-languages/sb/sb'
// import 'monaco-old/esm/vs/basic-languages/scala/scala'
import 'monaco-old/esm/vs/basic-languages/scheme/scheme'
import 'monaco-old/esm/vs/basic-languages/scss/scss'
import 'monaco-old/esm/vs/basic-languages/shell/shell'
// import 'monaco-old/esm/vs/basic-languages/solidity/solidity'
// import 'monaco-old/esm/vs/basic-languages/sophia/sophia'
// import 'monaco-old/esm/vs/basic-languages/sparql/sparql'
import 'monaco-old/esm/vs/basic-languages/sql/sql'
// import 'monaco-old/esm/vs/basic-languages/st/st'
import 'monaco-old/esm/vs/basic-languages/swift/swift'
// import 'monaco-old/esm/vs/basic-languages/systemverilog/systemverilog'
// import 'monaco-old/esm/vs/basic-languages/tcl/tcl'
// import 'monaco-old/esm/vs/basic-languages/twig/twig'
import 'monaco-old/esm/vs/basic-languages/typescript/typescript'
import 'monaco-old/esm/vs/basic-languages/vb/vb'
// import 'monaco-old/esm/vs/basic-languages/wgsl/wgsl'
import 'monaco-old/esm/vs/basic-languages/xml/xml'
import 'monaco-old/esm/vs/basic-languages/yaml/yaml'

export { monaco }